INSERT INTO PRICE (VEHICLE_ID,currency,price) VALUES (1,'USD',10000);
INSERT INTO PRICE (VEHICLE_ID,currency,price) VALUES (2,'USD',20000);
INSERT INTO PRICE (VEHICLE_ID,currency,price) VALUES (3,'USD',210000);
INSERT INTO PRICE (VEHICLE_ID,currency,price) VALUES (4,'USD',322000);
INSERT INTO PRICE (VEHICLE_ID,currency,price) VALUES (5,'RMB',322000);
INSERT INTO PRICE (VEHICLE_ID,currency,price) VALUES (6,'RMB',322000);
INSERT INTO PRICE (VEHICLE_ID,currency,price) VALUES (7,'ERU',322000);
INSERT INTO PRICE (VEHICLE_ID,currency,price) VALUES (8,'ERU',322000);